version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=https://api.openweathermap.org/data/2.5/weather?q=
      - SECRET_KEY=<your-openweathermap-api-key>
    volumes:
      - .:/app
      - /app/node_modules
